[package]
name = "rust_rational"
version = "0.1.0"
authors = ["Chris Dunphy <chris@megaparsec.ca>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
